// hoit.me 콘텐츠 카탈로그
// 모든 카테고리의 콘텐츠 메타데이터 (emoji, title, path)
// index.html의 GAMES/TESTS/DESTINY/ITKNOW/QUIZ/TOOLS/LEARN/CREATIVE 배열에서 추출

var CATALOG = {
  game: [
    {emoji:'🧱', title:'블록 쌓기', path:'games/tetris.html'},
    {emoji:'🐍', title:'뱀 키우기', path:'games/snake.html'},
    {emoji:'🐥', title:'날아라 병아리', path:'games/flappy.html'},
    {emoji:'🏰', title:'성 지키기', path:'games/tower_defense.html'},
    {emoji:'🎵', title:'리듬 스타', path:'games/rhythm.html'},
    {emoji:'🚀', title:'불렛 스톰', path:'games/bullet_storm.html'},
    {emoji:'⚫', title:'오목', path:'games/gomoku.html'},
    {emoji:'⛏️', title:'땅굴 탐험', path:'games/digging.html'},
    {emoji:'🔢', title:'2048', path:'games/puzzle2048.html'},
    {emoji:'💣', title:'지뢰찾기', path:'games/minesweeper.html'},
    {emoji:'🏓', title:'핑퐁', path:'games/pong.html'},
    {emoji:'🏃', title:'달려라!', path:'games/runner.html'},
    {emoji:'🃏', title:'기억력 게임', path:'games/memory.html'},
    {emoji:'🎯', title:'사격장', path:'games/shooting.html'},
    {emoji:'🧩', title:'슬라이딩 퍼즐', path:'games/sliding.html'},
    {emoji:'📝', title:'단어 맞추기', path:'games/hangman.html'},
    {emoji:'🧱', title:'벽돌깨기', path:'games/breakout.html'},
    {emoji:'🌈', title:'색 맞추기', path:'games/colormatch.html'},
    {emoji:'⌨️', title:'타자 게임', path:'games/typing.html'},
    {emoji:'🃏', title:'카드 배틀', path:'games/cardgame.html'},
    {emoji:'👆', title:'탭 스피드', path:'games/tap_speed.html'},
    {emoji:'🔨', title:'두더지 잡기', path:'games/whack.html'},
    {emoji:'🧺', title:'과일 받기', path:'games/catch.html'},
    {emoji:'📦', title:'블록 쌓기', path:'games/stack.html'},
    {emoji:'🫧', title:'버블 터뜨리기', path:'games/bubble.html'},
    {emoji:'💎', title:'스와이프 퍼즐', path:'games/swipe_match.html'},
    {emoji:'⚡', title:'반응속도 테스트', path:'games/reaction.html'},
    {emoji:'🏐', title:'공 피하기', path:'games/dodge_ball.html'},
    {emoji:'🔢', title:'숫자 순서 터치', path:'games/number_tap.html'},
    {emoji:'🌈', title:'컬러 스위치', path:'games/color_switch.html'},
    {emoji:'💣', title:'대포 대전', path:'games/fortress.html'},
    {emoji:'🧛', title:'몬스터 웨이브', path:'games/vampire.html'},
    {emoji:'🏎️', title:'레이싱', path:'games/racing.html'},
    {emoji:'🏝️', title:'무인도 생존', path:'games/survival.html'},
    {emoji:'⚔️', title:'던전 용사', path:'games/hackslash.html'},
    {emoji:'🧗', title:'절벽 올라가기', path:'games/climbing.html'},
    {emoji:'🏰', title:'미니 전략', path:'games/rts.html'},
    {emoji:'🃏', title:'블랙잭', path:'games/blackjack.html'},
    {emoji:'♠️', title:'텍사스 홀덤', path:'games/poker.html'},
    {emoji:'🂡', title:'솔리테어', path:'games/solitaire.html'},
    {emoji:'♟️', title:'체스', path:'games/chess.html'},
    {emoji:'🀄', title:'장기', path:'games/janggi.html'},
    {emoji:'🎯', title:'윷놀이', path:'games/yutnori.html'},
    {emoji:'⚫', title:'바둑', path:'games/baduk.html'},
    {emoji:'⚪', title:'오셀로', path:'games/othello.html'},
    {emoji:'🀄', title:'마작', path:'games/mahjong.html'},
    {emoji:'🎴', title:'섯다', path:'games/sutda.html'},
    {emoji:'🌸', title:'맞고', path:'games/matgo.html'},
    {emoji:'🎴', title:'고스톱', path:'games/gostop.html'},
    {emoji:'🏘️', title:'부루마블', path:'games/burumable.html'},
    {emoji:'🃏', title:'우노', path:'games/uno.html'},
    {emoji:'🔢', title:'스도쿠', path:'games/sudoku.html'},
    {emoji:'🎲', title:'야추', path:'games/yacht.html'},
    {emoji:'🎯', title:'다트', path:'games/dart.html'},
    {emoji:'🧩', title:'젠가', path:'games/jenga.html'},
    {emoji:'🃏', title:'원카드', path:'games/onecard.html'},
    {emoji:'🐺', title:'마피아', path:'games/mafia.html'},
    {emoji:'🎯', title:'루미큐브', path:'games/rummikub.html'},
    {emoji:'💥', title:'뱅', path:'games/bang.html'},
    {emoji:'✏️', title:'한붓그리기', path:'games/onestroke.html'},
  ],
  test: [
    {emoji:'🧠', title:'MBTI 테스트', path:'tests/mbti.html'},
    {emoji:'🩸', title:'혈액형 성격 분석', path:'tests/blood.html'},
    {emoji:'🎨', title:'색깔 심리 테스트', path:'tests/color.html'},
    {emoji:'💕', title:'연애 유형 테스트', path:'tests/love.html'},
    {emoji:'😰', title:'스트레스 지수', path:'tests/stress.html'},
    {emoji:'🦊', title:'동물 성격 테스트', path:'tests/animal.html'},
    {emoji:'⏳', title:'전생 테스트', path:'tests/pastlife.html'},
    {emoji:'🧠', title:'좌뇌우뇌 테스트', path:'tests/brain.html'},
    {emoji:'💼', title:'직업 적성 테스트', path:'tests/career.html'},
    {emoji:'💖', title:'감성지능(EQ) 테스트', path:'tests/eq.html'},
    {emoji:'📊', title:'DISC 성격 유형', path:'tests/disc.html'},
    {emoji:'🎉', title:'인싸/아싸 테스트', path:'tests/insider.html'},
    {emoji:'👑', title:'리더십 유형', path:'tests/leader.html'},
    {emoji:'💰', title:'금전감각 테스트', path:'tests/money.html'},
    {emoji:'✈️', title:'여행 유형 테스트', path:'tests/travel.html'},
    {emoji:'🍕', title:'음식 성격 테스트', path:'tests/food.html'},
    {emoji:'🎯', title:'집중력 테스트', path:'tests/focus.html'},
    {emoji:'🤝', title:'공감 능력 테스트', path:'tests/empathy.html'},
    {emoji:'👤', title:'첫인상 테스트', path:'tests/firstimp.html'},
    {emoji:'💪', title:'멘탈 강도 테스트', path:'tests/mental.html'},
  ],
  destiny: [
    {emoji:'⭐', title:'별자리 운세', path:'destiny/zodiac.html'},
    {emoji:'🔮', title:'타로 카드', path:'destiny/tarot.html'},
    {emoji:'🏮', title:'생년월일 운세', path:'destiny/saju.html'},
    {emoji:'🍀', title:'클로버 운세', path:'destiny/clover.html'},
    {emoji:'🎴', title:'화투 운세', path:'destiny/hwatu.html'},
    {emoji:'🌅', title:'오늘의 운수', path:'destiny/daily.html'},
    {emoji:'💭', title:'꿈 해몽', path:'destiny/dream.html'},
    {emoji:'🎲', title:'주사위 운세', path:'destiny/dice.html'},
    {emoji:'🪙', title:'동전 점', path:'destiny/coin.html'},
    {emoji:'🔢', title:'수비학', path:'destiny/numerology.html'},
    {emoji:'☯️', title:'오행 운세', path:'destiny/ohang.html'},
    {emoji:'👤', title:'관상 테스트', path:'destiny/face.html'},
    {emoji:'ᚱ', title:'룬 문자 운세', path:'destiny/rune.html'},
    {emoji:'🐱', title:'고양이 운세', path:'destiny/catfortune.html'},
    {emoji:'☕', title:'커피 운세', path:'destiny/coffee.html'},
    {emoji:'🌷', title:'꽃 운세', path:'destiny/flower.html'},
    {emoji:'🔄', title:'전생 운세', path:'destiny/pastlife_fortune.html'},
    {emoji:'🐺', title:'수호 동물', path:'destiny/spirit_animal.html'},
    {emoji:'📈', title:'바이오리듬', path:'destiny/biorhythm.html'},
    {emoji:'🎨', title:'오늘의 색 운세', path:'destiny/color_fortune.html'},
    {emoji:'🐚', title:'마법의 소라고동', path:'destiny/conch.html'},
  ],
  itknow: [
    {emoji:'🫧', title:'버블 정렬', path:'itknow/bubble_sort.html'},
    {emoji:'👆', title:'선택 정렬', path:'itknow/selection_sort.html'},
    {emoji:'📥', title:'삽입 정렬', path:'itknow/insertion_sort.html'},
    {emoji:'⚡', title:'퀵 정렬', path:'itknow/quick_sort.html'},
    {emoji:'🔀', title:'병합 정렬', path:'itknow/merge_sort.html'},
    {emoji:'📚', title:'스택', path:'itknow/stack_viz.html'},
    {emoji:'🚶', title:'큐', path:'itknow/queue_viz.html'},
    {emoji:'🔗', title:'링크드 리스트', path:'itknow/linkedlist_viz.html'},
    {emoji:'🌳', title:'이진 트리', path:'itknow/tree_viz.html'},
    {emoji:'#️⃣', title:'해시 테이블', path:'itknow/hash_viz.html'},
    {emoji:'🌐', title:'HTTP 원리', path:'itknow/http_explain.html'},
    {emoji:'🔍', title:'DNS 원리', path:'itknow/dns_explain.html'},
    {emoji:'🔐', title:'암호화 기초', path:'itknow/crypto_explain.html'},
    {emoji:'🔌', title:'API란?', path:'itknow/api_explain.html'},
    {emoji:'📝', title:'Git 기초', path:'itknow/git_explain.html'},
    {emoji:'💛', title:'JS 퀴즈', path:'itknow/js_quiz.html'},
    {emoji:'🐍', title:'Python 퀴즈', path:'itknow/python_quiz.html'},
    {emoji:'🗄️', title:'SQL 퀴즈', path:'itknow/sql_quiz.html'},
    {emoji:'🧮', title:'알고리즘 퀴즈', path:'itknow/algo_quiz.html'},
    {emoji:'🐛', title:'디버깅 퀴즈', path:'itknow/debug_quiz.html'},
  ],
  quiz: [
    {emoji:'🏯', title:'조선시대', path:'quiz/joseon.html'},
    {emoji:'🇰🇷', title:'근현대사', path:'quiz/modern.html'},
    {emoji:'👤', title:'역사 인물', path:'quiz/person.html'},
    {emoji:'🏛️', title:'문화재', path:'quiz/heritage.html'},
    {emoji:'📅', title:'연표', path:'quiz/timeline.html'},
    {emoji:'🚀', title:'우주', path:'quiz/space.html'},
    {emoji:'🫀', title:'인체', path:'quiz/body.html'},
    {emoji:'🦁', title:'동물', path:'quiz/animal.html'},
    {emoji:'⚗️', title:'화학', path:'quiz/chemistry.html'},
    {emoji:'⚡', title:'물리', path:'quiz/physics.html'},
    {emoji:'🏁', title:'국기 맞추기', path:'quiz/flags.html'},
    {emoji:'🏙️', title:'수도 맞추기', path:'quiz/capitals.html'},
    {emoji:'🍕', title:'세계 음식', path:'quiz/worldfood.html'},
    {emoji:'🗼', title:'랜드마크', path:'quiz/landmark.html'},
    {emoji:'🗣️', title:'세계 언어', path:'quiz/language.html'},
    {emoji:'😂', title:'밈 퀴즈', path:'quiz/meme.html'},
    {emoji:'💬', title:'신조어', path:'quiz/slang.html'},
    {emoji:'⭐', title:'연예인', path:'quiz/celeb.html'},
    {emoji:'🎬', title:'영화', path:'quiz/movie.html'},
    {emoji:'🎵', title:'음악', path:'quiz/music.html'},
  ],
  tools: [
    {emoji:'⚖️', title:'BMI 계산기', path:'tools/bmi.html'},
    {emoji:'🎂', title:'나이 계산기', path:'tools/age.html'},
    {emoji:'📅', title:'D-Day 계산기', path:'tools/dday.html'},
    {emoji:'💰', title:'더치페이 계산기', path:'tools/tip.html'},
    {emoji:'💱', title:'환율 계산기', path:'tools/exchange.html'},
    {emoji:'🎲', title:'닉네임 생성기', path:'tools/nickname.html'},
    {emoji:'🔑', title:'비밀번호 생성기', path:'tools/password.html'},
    {emoji:'📱', title:'QR코드 생성기', path:'tools/qrcode.html'},
    {emoji:'🎨', title:'색상 팔레트', path:'tools/palette.html'},
    {emoji:'📝', title:'한글 Lorem', path:'tools/lorem.html'},
    {emoji:'📐', title:'단위 변환기', path:'tools/unit.html'},
    {emoji:'🌈', title:'색상 변환기', path:'tools/color_convert.html'},
    {emoji:'🔢', title:'진법 변환기', path:'tools/base.html'},
    {emoji:'🔤', title:'인코딩 도구', path:'tools/encoding.html'},
    {emoji:'🕐', title:'시간대 변환', path:'tools/timezone.html'},
    {emoji:'⏱️', title:'타이머', path:'tools/timer.html'},
    {emoji:'⏲️', title:'스톱워치', path:'tools/stopwatch.html'},
    {emoji:'📋', title:'메모장', path:'tools/memo.html'},
    {emoji:'🎲', title:'주사위', path:'tools/dice_tool.html'},
    {emoji:'🪙', title:'동전 던지기', path:'tools/coin_tool.html'},
    {emoji:'📝', title:'글자수 세기', path:'tools/charcount.html'},
    {emoji:'🔄', title:'텍스트 변환', path:'tools/textconv.html'},
    {emoji:'📋', title:'JSON 포맷터', path:'tools/jsonformat.html'},
    {emoji:'📄', title:'마크다운 미리보기', path:'tools/markdown.html'},
    {emoji:'🔍', title:'정규식 테스터', path:'tools/regex.html'},
    {emoji:'%', title:'퍼센트 계산기', path:'tools/percent.html'},
    {emoji:'📆', title:'날짜 계산기', path:'tools/datecalc.html'},
    {emoji:'🏦', title:'대출 계산기', path:'tools/loan.html'},
    {emoji:'💵', title:'연봉 실수령액', path:'tools/salary.html'},
    {emoji:'🍺', title:'음주 계산기', path:'tools/alcohol.html'},
    {emoji:'🌈', title:'CSS 그라데이션', path:'tools/gradient.html'},
    {emoji:'🖼️', title:'이미지 리사이즈', path:'tools/imgresize.html'},
    {emoji:'📦', title:'이미지 압축', path:'tools/imgcompress.html'},
    {emoji:'🎨', title:'화이트보드', path:'tools/whiteboard.html'},
    {emoji:'🍅', title:'포모도로 타이머', path:'tools/pomodoro.html'},
    {emoji:'🧘', title:'호흡 가이드', path:'tools/breathing.html'},
    {emoji:'🎰', title:'랜덤 룰렛', path:'tools/roulette.html'},
    {emoji:'✅', title:'할일 목록', path:'tools/todo.html'},
    {emoji:'📊', title:'습관 트래커', path:'tools/habit.html'},
    {emoji:'🔊', title:'백색소음', path:'tools/noise.html'},
  ],
  health: [
    {emoji:'🏋️', title:'운동 타이머', path:'health/workout.html'},
    {emoji:'🍎', title:'칼로리 계산', path:'health/calories.html'},
    {emoji:'🧘', title:'스트레칭 가이드', path:'health/stretch.html'},
    {emoji:'💧', title:'물 마시기', path:'health/water.html'},
    {emoji:'😴', title:'수면 계산기', path:'health/sleep.html'},
  ],
  learn: [
    {emoji:'🔤', title:'영어 단어장', path:'learn/english.html'},
    {emoji:'✖️', title:'구구단 연습', path:'learn/gugudan.html'},
    {emoji:'📜', title:'사자성어 퀴즈', path:'learn/idiom.html'},
    {emoji:'💬', title:'속담 퀴즈', path:'learn/proverb.html'},
    {emoji:'⌨️', title:'타자 속도 측정', path:'learn/typing_practice.html'},
    {emoji:'🇯🇵', title:'일본어 한 문장', path:'learn/japanese.html'},
    {emoji:'🇪🇸', title:'스페인어 한 문장', path:'learn/spanish.html'},
    {emoji:'🇺🇸', title:'영어 한 문장', path:'learn/english_daily.html'},
  ],
  reading: [
    {emoji:'💬', title:'명언 생성기', path:'reading/quotes.html'},
    {emoji:'📖', title:'짧은 이야기', path:'reading/stories.html'},
    {emoji:'❓', title:'수수께끼', path:'reading/riddles.html'},
    {emoji:'👅', title:'잰말 연습', path:'reading/tongue.html'},
    {emoji:'📝', title:'오늘의 일기', path:'reading/diary.html'},
  ],
  creative: [
    {emoji:'🎨', title:'픽셀아트', path:'creative/pixel.html'},
    {emoji:'💻', title:'아스키아트', path:'creative/ascii.html'},
    {emoji:'🧪', title:'이모지 믹서', path:'creative/emoji_mix.html'},
    {emoji:'👤', title:'아바타 만들기', path:'creative/avatar.html'},
  ],
  music: [
    {emoji:'🎵', title:'메트로놈', path:'music/metronome.html'},
    {emoji:'🎹', title:'피아노', path:'music/piano.html'},
    {emoji:'🎸', title:'기타 코드표', path:'music/chords.html'},
    {emoji:'🎼', title:'음 주파수표', path:'music/tuner.html'},
    {emoji:'🥁', title:'드럼 패드', path:'music/drums.html'},
  ],
};
